export default {
    products: [{
            _id: '1',
            name: 'shirt ',
            category: 'shirt',
            brand: 'nike',
            image: '/images/d1.jpg',
            price: 30,
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
        },
        {
            _id: '2',
            name: 'slim ',
            category: 'shirt',
            brand: 'nike',
            image: '/images/d1.jpg',
            price: 50,
            rating: 4.5,
            numReviews: 8,
            countInStock: 6,
        }, {
            _id: '3',
            name: 'slim ',
            category: 'shirt',
            brand: 'nike',
            image: '/images/d1.jpg',
            price: 30,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        }, {
            _id: '4',
            name: 'slim ',
            category: 'pants',
            brand: 'nike',
            image: '/images/d1.jpg',
            price: 30,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'slim ',
            category: 'shirt',
            brand: 'nike',
            image: '/images/d1.jpg',
            price: 50,
            rating: 4.5,
            numReviews: 8,
            countInStock: 6,
        }, {
            _id: '6',
            name: 'slim ',
            category: 'shirt',
            brand: 'nike',
            image: '/images/d1.jpg',
            price: 30,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        }, {
            _id: '5',
            name: 'slim ',
            brand: 'nike',
            category: 'pants',
            image: '/images/d1.jpg',
            price: 30,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ]
}